name: education
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  translator_plus: ^1.0.1
  html_unescape: ^2.0.0
  shared_preferences: ^2.1.0
  flutter_tts: ^4.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/data/stories.json
    - assets/data/local_en_vi.json
    - assets/data/local_vi_en.json
